### ISSUE TITLE
Consider using \s instead of the space character in regexes

### ISSUE THREAD

**Issue by alopezlago** [geoffrey-wu/qb-packet-parser#5]
https://github.com/thedoge42/qb-packet-parser/blob/091cd78efbe1e28bb14142e71548caa1da401b0c/parser.py#L117

Consider using `\s` instead of the space character, which will handle things like tabs and non-breaking spaces that may sometimes crop up in packets.

**Comment by geoffrey-wu** [comment]
I decided to rewrite the main regex to be more robust—making fewer assumptions about the underlying packet format and making each question more "self-contained": 645fe1b3c6f4c6665888e2fa3f4413cdbeda92ec
